# Server configuration
server.port=8088

# Application name
spring.application.name=simple-queuing-service

# Logging
logging.level.root=INFO
logging.level.com.solace.samples.queuingservice=DEBUG

# Jackson JSON configuration
spring.jackson.serialization.indent-output=true
spring.jackson.default-property-inclusion=non_null

# OpenAPI documentation
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
